"""Add specs and guarantees

Revision ID: 76f56751a37a
Revises: 
Create Date: 2026-02-22 16:21:08.719541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f56751a37a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('guarantees', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('guarantees')
        batch_op.drop_column('specs')

    # ### end Alembic commands ###
